language: python
python:
    - "2.7"
install:
    # Install Conda
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes yes --set changeps1 no
    - conda update conda

    - conda env create -n accessibleml
    - source activate accessibleml

script:
    - py.test

notifications:
    email: false
    slack:
        rooms:
            - adicu:ZYh6piN2eWh1yFvDygDxcJjt
        on_success: change
        on_failure: change
        on_pull_requests: false
